from .awal_handler import *
from .tambah_admin import *
from .send_handler import * 
from .ban_handler import *
from .bot_handler import *
from .talent_handler import *
from .daddy_sugar import *
from .proplayer import *
from .teman_curhat import *
from .boyfriend_rent import *
from .girlfriend_rent import *
from .broadcast_handler import *
from .status import *